spring:
  data:
    mongodb:
      uri: mongodb://14.138.114.106:20530
      database: nkakao
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
server:
  port: 8081